config/routes.rb
Rails.application.routes.draw do


  ActiveAdmin.routes(self)

  root to: 'pages#home'

  get '/participants', to: 'bookings#new'
  post '/participants', to: 'bookings#new'

  get '/results', to: 'pages#results'
  # post '/results', to: 'pages#results'

  devise_scope :user do
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                   registrations: 'registrations'}


  resources :profiles, only: [:update, :show] do
    resources :bookings, only: [:index, :show]
  end

  get 'profile', to: "profiles#edit", as: :edit_profile

  resources :trainings

  resources :trainings, only: [:new, :edit] do
    resources :sessions, only: [:new, :create, :index]
  end



  resources :sessions, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :update, :destroy, :edit]
  end

  resources :requests

  resources :sports

  resources :trainers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/training.rb
class Training < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  scope :cheap, -> { where("price < ?", 15).limit(2) }

  belongs_to :sport
  belongs_to :profile

  has_many :sessions, dependent: :destroy

  validates :sport, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :duration, presence: true
  validates :price, presence: true
  validates :group_capacity, presence: true
  validates :level, presence: true
  validates :address, presence: true

  def average_reviews
    numerator = 0
    denominator = 0
    total = 0
    n = 0
    self.sessions.each do |session|
      unless session.average_reviews.nil?
        n += session.reviews.count
        numerator += session.average_reviews[:average_score] * session.average_reviews[:number]
        denominator += session.average_reviews[:number]
      end
    end
    if denominator != 0
      (total = numerator / denominator)
    else
      total = 0
    end
    {
      average_score: total,
      number: n
    }
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :load_training, only: [:show, :edit, :update, :destroy, :load_sessions]
  before_action :load_sessions, only: [:show, :edit, :update, :destroy]


  def index
    @trainings = current_profile.trainings
  end

  def show
    @hash = Gmaps4rails.build_markers(@training) do |training, marker|
      marker.lat @training.latitude
      marker.lng @training.longitude
    end
    @booking = Booking.new
  end

  def new
    @sports = Sport.all
    @training = Training.new
  end

  def create
    @training = Training.new(training_params)
    @training.profile = current_user.profile
    # session[:training] = @training
    if @training.save
      redirect_to new_training_session_path(@training)
      flash[:notice] = "Please finish your training registration by adding sessions"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @training = Training.new(training_params)
    @training.profile = current_user.profile
    if @training.save
      redirect_to trainings_path
    else
      render :edit
    end
  end

  def destroy
    @training.destroy
    redirect_to :back
  end

  private
  def training_params
    params.require(:training).permit(:sport_id, :title, :date, :time, :duration, :price, :group_capacity, :level, :description, :outdoor, :longitude, :lattitude, :country, :city, :address, :zip_code)
  end

  def load_training
    @training = Training.find(params[:id])
  end

  def load_sessions
    @sessions = @training.sessions
  end

end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_training-show.html.erb
<div class="training-all-details">
<div class="training-border">
 </div>
  <div class="training-tabs">
    <% ["Training", "Trainer", "Reviews", "Location"].each_with_index do |tab_name, i| %>
      <div class="training-tab <%= 'active' if i == 0 %>" data-target=".<%= tab_name.downcase %>-content">
        <%= tab_name %>
      </div>
    <% end %>
  </div>
  <div class="training-content">
    <% ["Training", "Trainer", "Reviews", "Location"].each_with_index do |tab_name, i| %>
      <div class="<%= tab_name.downcase %>-content training-tab-contents <%= 'hidden' if i >= 1 %>">
        <%= render partial: "trainings/shared/#{tab_name.downcase}" %>
      </div>
    <% end %>
  </div>
</div>

app/views/trainings/edit.html.erb
<div class="form-container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= simple_form_for @training, method: :patch do |f| %>
      <div class="form-inputs">
        <%= f.input :title %>
        <%= f.input :description %>
      <div class="form-actions">
      <%= f.button :submit, "Save your trainings", class: "btn black-button" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/trainings/index.html.erb
<%= render "shared/profile-tabs" %>

<div class="training-container">
  <% if current_profile.trainer.nil? && current_profile.request.nil? %>
  <p>You are not a trainer yet!</p>
  <%= link_to "Become a trainer", new_request_path, class: "navbar-wagon-button" %>
  <% elsif !current_profile.request.nil? %>
  <p>Your request to become a trainer is being reviewed</p>
  <% else %>
  <div class="create-training text-center">
    <%= link_to "Create a new training!", new_training_path, class: "navbar-wagon-button text-center btn" %>
  </div>
  <div class="container">
    <div class="row">
      <% @trainings.each do |training| %>
      <div class="col-xs-12 col-sm-4">
       <%= training.title %>
       <%= training.description %>
       <%= link_to "details", training_path(training) %>
       <% end %>
      </div>
    </div>
  </div>
 <% end %>
</div>

app/views/trainings/new.html.erb
<div class="form-container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
    <h2 id="training-title">Add a training</h2>
      <p>Please enter the details for this training</p>
      <%= simple_form_for(@training) do |f| %>
      <%= f.input :sport_id, collection: @sports, prompt: "Pick a sport", label: false %>
      <%= f.input :title, autofocus: true, placeholder: "Enter a title", label: false %>
      <%= f.input :description, placeholder: "Enter a description", label: false %>
      <%= f.input :duration, placeholder: "How long is your training?", label: false %>
      <%= f.input :price, placeholder: "What is the price?", label: false %>
      <%= f.input :group_capacity, placeholder: "How many people can join your training?", label: false %>
      <%= f.input :level, collection: ["Beginner", "Medium", "Difficult"], prompt: "What is the difficulty level?", label: false %>
      <%= f.input :outdoor %>
      <%= f.input :address, placeholder: "What is the address of training?", label: false %>
      <%= f.button :submit, "Set training sessions for this training", class: "black-button submit-button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/trainings/show.html.erb
<div class="training-banner">
  <div class="training-banner" style="background-image: url('<%= cl_image_path @training.profile.trainer.banner_picture %>')">
  </div>
</div>

<div class="wrapper-training">

  <%= render 'trainings/training-show' %>

  <div class="training-booking">
    <div class="sessions">
      <h4>Training's sessions: </h4>
      <% previous = @sessions.first %>
      <% @sessions.each do |session| %>

      <% if session.date.strftime("%Y-%m-%d") != previous.date.strftime("%Y-%m-%d") or @sessions.first == session %>
      <h4>
        <%= session.date.strftime("%a, %e %b %Y") %>
      </h4>
      <br>
      <h4>Select a time:</h4>
      <br>
      <% end %>

      <%= link_to "#{session.time.strftime("at %H:%M")}", "#", data: { toggle: "modal", target: "#myConfirmModal#{session.id}" },class: "blue-button" %>

      <% previous = session %>
      <%= render partial: 'shared/confirm', locals: { session: session } %>
      <% end %>

    </div>
  </div>
</div>

<style>
  .footer{
    display: none;
  }
</style>



<!-- action=url method=post/get/patch
forms bunch of input
submit -> build a hash, send it to the url


simple_form_for object.analyze = kind of object, then it knows what controller to go to:
@booking, @session,

then it knows to go to a nested route.

booking class -> booking controller

if object is empty -> create
if data -> update  -->