config/routes.rb
Rails.application.routes.draw do


  ActiveAdmin.routes(self)

  root to: 'pages#home'

  get '/participants', to: 'bookings#new'
  post '/participants', to: 'bookings#new'

  get '/results', to: 'pages#results'
  # post '/results', to: 'pages#results'

  devise_scope :user do
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                   registrations: 'registrations'}


  resources :profiles, only: [:update, :show] do
    resources :bookings, only: [:index, :show]
  end

  get 'profile', to: "profiles#edit", as: :edit_profile

  resources :trainings

  resources :trainings, only: [:new, :edit] do
    resources :sessions, only: [:new, :create, :index]
  end



  resources :sessions, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :update, :destroy, :edit]
  end

  resources :requests

  resources :sports

  resources :trainers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :trainings, dependent: :destroy
  has_many :sessions, through: :trainings

  mount_uploader :banner_sport_picture, PhotoUploader

  validates :name, presence: true
  validates :tagline, presence: true
  validates :description, presence: true
  validates :banner_sport_picture, presence: true
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController

  before_action :load_sport, only: [:show, :edit, :update, :destroy]

  def index
    @sports = Sport.all
  end

  def show
  end

  def new
    @sport = Sport.new
  end

  def create
    @sport = Sport.new(sport_params)
    if @sport.save
      redirect_to sports_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @sport.destroy
    redirect_to root_path
  end

  private
  def load_sport
    @sport = Sport.find(params[:id])
  end

  def sport_params
    params.require(:sport).permit(:name, :description, :tagline, :banner_sport_picture, :banner_sport_picture_cache)
  end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/edit.html.erb
<div class="form-container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <%= simple_form_for(@sport) do |f| %>
      <%= f.input :name, required: true %>
      <%= f.input :tagline, required: true %>
      <%= f.input :description, required: true %>
      <%= f.input :banner_sport_picture, required: true %>
      <%= f.input :banner_sport_picture_cache, as: :hidden %>
      <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/sports/index.html.erb
<% @sports.each do |sport| %>
  <%= sport.name %>
<% end %>

app/views/sports/new.html.erb
<div class="form-container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <%= simple_form_for(@sport) do |f| %>
      <%= f.error_notification %>
      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :tagline %>
        <%= f.input :description %>
        <%= f.input :banner_sport_picture %>
        <%= f.input :banner_sport_picture_cache, as: :hidden %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Save sport",
        class: "btn black-button" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/sports/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= @sport.name %>
      <%= @sport.description %>
      <%= @sport.tagline %>
      <%= link_to "Delete", sport_path(@sport), method: :delete %>
    </div>
  </div>
</div>