config/routes.rb
Rails.application.routes.draw do


  ActiveAdmin.routes(self)

  root to: 'pages#home'

  get '/participants', to: 'bookings#new'
  post '/participants', to: 'bookings#new'

  get '/results', to: 'pages#results'
  # post '/results', to: 'pages#results'

  devise_scope :user do
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                   registrations: 'registrations'}


  resources :profiles, only: [:update, :show] do
    resources :bookings, only: [:index, :show]
  end

  get 'profile', to: "profiles#edit", as: :edit_profile

  resources :trainings

  resources :trainings, only: [:new, :edit] do
    resources :sessions, only: [:new, :create, :index]
  end



  resources :sessions, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :update, :destroy, :edit]
  end

  resources :requests

  resources :sports

  resources :trainers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :profile
  mount_uploader :banner_picture, PhotoUploader

  validates :banner_picture, presence: true
  validates :description, presence: true
  validates :bio, presence: true
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :load_request, only: [:show, :edit, :destroy]


  def new
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    @request.profile = current_user.profile
    if @request.valid?
      @request.save
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @requests = Request.all
  end

  def show
  end

  def destroy
    @request.destroy
  end

  def edit
  end

  def update
    @request.update_attributes(request_params)
    if @request.valid?
      @request.save
      redirect_to requests_path
    else
      render :edit
    end
  end

  private

  def request_params
    params.require(:request).permit(:certificates, :education, :bio, :banner_picture, :banner_picture_cache, :description)
  end

  def load_request
    @request = Request.find(params[:id])
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/edit.html.erb
<div class="form-container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <%= simple_form_for @request, method: :patch do |f| %>
      <%= f.input :description %>
      <%= f.input :bio %>
      <%= f.input :certificates %>
      <%= f.input :education %>
      <%= f.input :banner_picture %>
      <%= f.input :banner_picture_cache, as: :hidden %>
      <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/requests/index.html.erb
<% @requests.each do |request| %>
  <%= request.description %>
  <%= link_to "evaluate the request", request_path(request) %>
<% end %>

app/views/requests/new.html.erb
<div class="form-container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
    <h2 id="trainer-title">Become a trainer!</h2>
      <%= simple_form_for(@request) do |f| %>
      <%= f.input :description, autofocus: true, placeholder: "Tagline", label: false %>
      <%= f.input :bio, autofocus: true, placeholder: "Can you tell us a bit more about yourself?", label: false %>
      <%= f.input :certificates, autofocus: true, placeholder: "Do you have any certificates?", label: false %>
      <%= f.input :education, autofocus: true, placeholder: "Education", label: false %>
      <%= f.input :banner_picture %>
      <%= f.input :banner_picture_cache, as: :hidden %>
      <%= f.button :submit, "Submit", class: "black-button submit-button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/requests/show.html.erb
<%= @request.description %>
<%= @request.bio %>

<%= link_to "Accept this trainer", trainers_path(request: @request), method: :post %>