config/routes.rb
Rails.application.routes.draw do


  ActiveAdmin.routes(self)

  root to: 'pages#home'

  get '/participants', to: 'bookings#new'
  post '/participants', to: 'bookings#new'

  get '/results', to: 'pages#results'
  # post '/results', to: 'pages#results'

  devise_scope :user do
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                   registrations: 'registrations'}


  resources :profiles, only: [:update, :show] do
    resources :bookings, only: [:index, :show]
  end

  get 'profile', to: "profiles#edit", as: :edit_profile

  resources :trainings

  resources :trainings, only: [:new, :edit] do
    resources :sessions, only: [:new, :create, :index]
  end



  resources :sessions, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :update, :destroy, :edit]
  end

  resources :requests

  resources :sports

  resources :trainers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :session
  belongs_to :profile
  has_one :review
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: "Profile"
  belongs_to :receiver, class_name: "Profile"
end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :avatar_picture, PhotoUploader

  belongs_to :user
  has_one :request
  belongs_to :trainer, optional: true
  has_many :trainings, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  # has_many :messages, dependent: :destroy

  def average_reviews
    numerator = 0
    denominator = 0
    total = 0
    n = 0
    self.trainings.each do |training|
      unless training.average_reviews.nil?
        n += training.average_reviews[:number]
        numerator += training.average_reviews[:average_score] * training.average_reviews[:number]
        denominator += training.average_reviews[:number]
      end
    end
    if denominator != 0
      (total = numerator / denominator)
      total
    else
      "No reviews"
    end
  end
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :profile
  mount_uploader :banner_picture, PhotoUploader

  validates :banner_picture, presence: true
  validates :description, presence: true
  validates :bio, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :profile
  has_one :session, through: :booking
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :training

  has_one :sport, through: :training
  has_many :bookings
  has_many :reviews, through: :bookings

  def available_spots
    total = 0
    self.bookings.each do |booking|
      total += booking.participants
    end
    self.group_capacity - total
  end

  def average_reviews
    if self.reviews.empty?
      return nil
    else
      n = 0
      total = 0
      average = 0
      self.reviews.each do |review|
        n += 1
        total += review.rating.to_f
      end
      average = (total / n).to_f
      {
        number: n,
        average_score: average.to_f
      }
    end
  end
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :trainings, dependent: :destroy
  has_many :sessions, through: :trainings

  mount_uploader :banner_sport_picture, PhotoUploader

  validates :name, presence: true
  validates :tagline, presence: true
  validates :description, presence: true
  validates :banner_sport_picture, presence: true
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  mount_uploader :banner_picture, PhotoUploader
  has_one :profile


end

app/models/training.rb
class Training < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  scope :cheap, -> { where("price < ?", 15).limit(2) }

  belongs_to :sport
  belongs_to :profile

  has_many :sessions, dependent: :destroy

  validates :sport, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :duration, presence: true
  validates :price, presence: true
  validates :group_capacity, presence: true
  validates :level, presence: true
  validates :address, presence: true

  def average_reviews
    numerator = 0
    denominator = 0
    total = 0
    n = 0
    self.sessions.each do |session|
      unless session.average_reviews.nil?
        n += session.reviews.count
        numerator += session.average_reviews[:average_score] * session.average_reviews[:number]
        denominator += session.average_reviews[:number]
      end
    end
    if denominator != 0
      (total = numerator / denominator)
    else
      total = 0
    end
    {
      average_score: total,
      number: n
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # after_create :send_welcome_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :omniauthable, omniauth_providers: [:facebook]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile, dependent: :destroy


  def self.find_for_facebook_oauth(auth)
    email = auth.info.email

    if not email.present?
      email = "#{Devise.friendly_token[0,20]}@email.com"
    end

    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: email).first # User did a regular sign up in the past.

    attributes = {
                    first_name: auth.info.first_name,
                    last_name: auth.info.last_name,
                  }

    if user
      user.update(user_params)
      user.profile.update({remote_avatar_picture_url: auth.info.image})
    else
      user = User.new(user_params)
      user.email = email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save

      profile = Profile.new(attributes)
      profile.user = user
      profile.remote_avatar_picture_url = auth.info.image
      profile.save
    end

    return user
  end

  def name
    self.email
  end

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/layouts/_banner.html.erb
<div class="hidden-xs">
  <div class="banner-container">
    <div class="banner-content">
      <div class="banner-title">
        <h1>
         Soplex
       </h1>
       <h3>
           Train Whenever, Wherever
         </h3>
         </div>
         <div class="btn-down fa fa-chevron-down fa-3x" aria-hidden="true" onclick="">
      </div>
      <div class="form-inline search-field-banner text-center">
        <%= simple_form_for :search_query, url: results_path, method: :get do |f| %>
        <div class="form-inputs">
          <%= f.input :sport, autofocus: true, collection: @sports_selection, prompt: "Pick a sport  ▾", label: false %>
          <%= f.input :date, as: :date_picker, placeholder: "Pick a date", label: false %>
          <%= f.button :submit, "Search", class: "search-button form-inline" %>
        </div>
        <% end %>
      </div>
      </div>
    <div class="banner-photo" style="background-image: url(<%= image_url 'woman-running-park-sunset1.jpg'%>);">
    </div>
  </div>
</div>

<div class="hidden-sm hidden-md hidden-lg">
  <div class="banner-photo-xs" style="background-image: url(<%= image_url 'woman-running-park-sunset1.jpg'%>);">
  </div>
  <div class="banner-title-xs">
    <h1 class="text-center">
     Soplex
   </h1>
   <h4 class="text-center" id="xs-tagline">
     Train Whenever, Wherever
   </h4>
 </div>
 <div class=" xs-banner search-field-banner">
  <%= simple_form_for :search_query, url: results_path, method: :get do |f| %>
  <div class="text-center form-inputs">
    <%= f.input :sport, autofocus: true, collection: @sports, prompt: "Pick a sport ▼", label: false, class: "black-button" %>
    <%= f.input :date, as: :date_picker, placeholder: "Pick a date", label: false %>
    <%= f.button :submit, "Search", class: " search-button navbar-wagon-button form-inline" %>
  </div>
  <% end %>
</div>


</div>

app/views/layouts/_footer.html.erb
<div class="footer hidden-xs">
  <div class="social-buttons">
    <ul class="social-button">
      <li><%= link_to '<i class="fa fa-facebook fa-lg"></i>'.html_safe, root_path %></li>
      <li><%= link_to '<i class="fa fa-twitter fa-lg"></i>'.html_safe, root_path %></li>
      <li><%= link_to '<i class="fa fa-instagram fa-lg"></i>'.html_safe, root_path %></li>
      <li><%= link_to '<i class="fa fa-pinterest fa-lg"></i>'.html_safe, root_path %></li>
    </ul>
  </div>
  <div>
    <ul class="footer-text">
      <li> <%= link_to "Terms and Conditions" %></li>
      <li> <%= link_to "About Soplex" %></li>
      <li> <%= link_to "Privacy" %></li>
      <li> <%= link_to "Disclaimer" %></li>
      <li> &copy 2017</li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
    <title>
      Soplex - Train Whenever, Wherever
    </title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
<!--     <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%#= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%#= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>"> -->

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body class="Site">

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= render 'shared/sign-up' %>
    <%= render 'shared/login' %>
    <main class="Site-content">
      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '453225988402267',
          cookie     : true,
          xfbml      : true,
          version    : 'v2.8'
        });
        FB.AppEvents.logPageView();
      };

      (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "//connect.facebook.net/en_US/sdk.js";
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));
    </script>
  </body>
</html>

app/views/shared/_confirm.html.erb
<div class="modal fade" id="myConfirmModal<%= session.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div class="modal-title text-center"> <%= image_tag "logo-soplex.png", height: 40 %></div>
      </div>
      <div class="modal-body">
        <%= render partial: 'bookings/new', locals: { session: session } %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_login.html.erb
<div class="modal fade" id="myLoginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div class="modal-title text-center"> <%= image_tag "logo-soplex.png", height: 40 %></div>
      </div>
      <div class="modal-body modal-padding">
        <div class=" text-center button-margin">
          <%- if devise_mapping.omniauthable? %>
          <%- resource_class.omniauth_providers.each do |provider| %>
          <%= link_to omniauth_authorize_path(resource_name, provider), class: "black-button fb-button" do %>
          <i class="fa fa-facebook"></i> Log in with <%= OmniAuth::Utils.camelize(provider) %>
          <% end %>
          <% end -%>
          <% end -%>
        </div>
        <div class="alt-to-fb">
          <h4 class="text-center">or</h4 class="text-center">
          </div>
          <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>

          <div class="form-inputs">
            <%= f.input :email, required: false, autofocus: true, placeholder: "Enter email", label: false %>
            <%= f.input :password, required: false,  placeholder: "Enter password", label: false %>
            <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Log in", class: "black-button submit-button" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo-soplex.png" %>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
    <!-- Profile picture and dropdown -->
    <% if current_profile.trainer_id.nil? %>
    <%= link_to t(".top_call_to_action", default: "Become a trainer?"), new_request_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% end %>

    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if current_profile.avatar_picture.present? %>
        <img src="<%= cl_image_path current_profile.avatar_picture, crop: :fill, height: 32, width: 32 %>" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <% else %>
        <img src="<%= image_url 'blue.jpg', crop: :fill %>" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to edit_profile_path do %>
            <%= t(".profile", default: "Edit profile") %>
            <% end %>
          </li>
          <% if current_profile.trainer_id %>
          <li>
            <%= link_to trainer_path(current_profile) do %>
            <%= t(".profile", default: "Show trainer profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to new_training_path do %>
            <%= t(".profile", default: "Add a training") %>
            <% end %>
          </li>
          <li>
            <%= link_to trainings_path do %>
            <%= t(".profile", default: "All your trainings") %>
            <% end %>
          </li>
          <% end %>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>



    <% else %>

    <%= link_to t(".top_call_to_action", default: "Become a trainer?"), new_request_path, class: "navbar-wagon-item navbar-wagon-button btn" %>

    <%= link_to 'Login',  "#", data: { toggle: "modal", target: "#myLoginModal" },class: "navbar-wagon-item navbar-wagon-button btn" %>


    <%= link_to 'Sign up',  "#", data: { toggle: "modal", target: "#mySignUpModal" },class: "navbar-wagon-item navbar-wagon-button btn" %>

    <% end %>
  </div

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
        <% if current_profile.trainer_id %>
        <li><%= link_to "Profile", edit_profile_path %></li>
        <li><%= link_to "Trainer profile", edit_trainer_path(current_profile) %></li>
        <li><%= link_to "Add a training", new_training_path %></li>
        <li><%= link_to "All your trainings", trainings_path %></li>
        <% end %>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li> <%= link_to 'Sign up',  "#", data: { toggle: "modal", target: "#mySignUpModal" } %> </li>
        <li> <%= link_to 'Login',  "#", data: { toggle: "modal", target: "#myLoginModal" } %> </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_profile-tabs.html.erb
<div class="tabs">

  <%= active_link_to "Profile", edit_profile_path, class: "tab black-tab" %>
  <% if current_profile.trainer_id %>
  <%= active_link_to "Trainer Profile", edit_trainer_path(current_profile), class: "tab black-tab" %>
  <%= active_link_to "Your trainings", trainings_path, class: "tab black-tab" %>
  <% end %>
  <%= active_link_to "Your Bookings", bookings_path, class: "tab black-tab" %>
</div>

app/views/shared/_sign-up.html.erb
<div class="modal fade" id="mySignUpModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div class="modal-title text-center"> <%= image_tag "logo-soplex.png", height: 40 %></div>
      </div>
      <div class="modal-body modal-padding">
        <div class=" text-center button-margin">
          <%- if devise_mapping.omniauthable? %>
          <%- resource_class.omniauth_providers.each do |provider| %>
          <%= link_to omniauth_authorize_path(resource_name, provider), class: "black-button fb-button" do %>
          <i class="fa fa-facebook"></i> Sign up with <%= OmniAuth::Utils.camelize(provider) %>
          <% end %>
          <% end -%>
          <% end -%>
        </div>
        <div class="alt-to-fb">
          <h4 class="text-center">or</h4 class="text-center">
          </div>

          <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= f.error_notification %>

          <% if f.error_notification %>
          <div class="form-inputs validation-failed" id="validation-sign-up">
            <% else %>
            <div class="form-inputs" id="validation-sign-up">
              <% end %>
              <%= f.input :email, required: true, autofocus: true, placeholder: "Enter email", label: false %>
              <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length), placeholder: "Enter password", label: false %>
              <%= f.input :password_confirmation, required: true, placeholder: "Repeat password", label: false %>
            </div>
          </div>
          <div class="modal-footer">
           <div class="form-actions">
            <%= f.button :submit, "Sign up", class: "black-button sign-up-button" %>
          </div>

          <% end %>
          <div class="modal-text">
           <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
           <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
           <% end -%>
         </div>
       </div>
     </div>
   </div>
 </div>